FROM archlinux:base-devel

ARG UID=1000
ARG GID=1000

RUN pacman -Syu --noconfirm --needed \
        git devtools expac jq curl cmake ninja clang lld \
        bc cpio perl python xz zstd libelf openssl pahole kmod \
        gnupg sudo libarchive arch-install-scripts \
    && pacman -Scc --noconfirm

RUN groupadd -o -g "$GID" builder \
    && useradd -o -m -u "$UID" -g "$GID" -s /bin/bash builder \
    && echo 'builder ALL=(ALL) NOPASSWD: ALL' > /etc/sudoers.d/builder \
    && chmod 440 /etc/sudoers.d/builder

USER builder
ENV HOME=/home/builder
WORKDIR /work